In [1]:
import random
import numpy as np

In [2]:
matrix = [ [random.randint(1, 99) for k in range(8)] for i in range(3)] #dvostruki list comprehension kako bi se kreirala matrica

In [3]:
matrix

[[9, 34, 83, 2, 10, 96, 58, 85],
 [75, 61, 4, 94, 18, 27, 60, 79],
 [26, 63, 64, 32, 17, 26, 95, 66]]

In [4]:
matrix_np = np.array(matrix)

Lako se može matrica predstavljena numpy nizom transponovati:

In [5]:
matrix_np.T

array([[ 9, 75, 26],
       [34, 61, 63],
       [83,  4, 64],
       [ 2, 94, 32],
       [10, 18, 17],
       [96, 27, 26],
       [58, 60, 95],
       [85, 79, 66]])

numpy niz ima atribut `shape` koji sadrži informaciju o dimenzijama niza:

In [6]:
matrix_np.shape

(3, 8)

Metod `reshape()` modifikuje dimenzije niza nad kojim se poziva u proslijeđene dimenzije. Niz je moguće predimenzionisati samo u odgovarajuće dimenzije, tj. proizvod proslijeđenih dimenzija mora biti jednak proizvodu početnih dimenzija. Takođe broj dimenzija ne mora biti jednak početnom.

In [7]:
matrix_np.reshape(4, 3, 2)

array([[[ 9, 34],
        [83,  2],
        [10, 96]],

       [[58, 85],
        [75, 61],
        [ 4, 94]],

       [[18, 27],
        [60, 79],
        [26, 63]],

       [[64, 32],
        [17, 26],
        [95, 66]]])

Ovom metodu je moguće kao parametar proslijediti `-1` u slučaju kad nismo sigurni koja je preostala dimenzija.

In [8]:
matrix_np.reshape(-1, 3, 2)

array([[[ 9, 34],
        [83,  2],
        [10, 96]],

       [[58, 85],
        [75, 61],
        [ 4, 94]],

       [[18, 27],
        [60, 79],
        [26, 63]],

       [[64, 32],
        [17, 26],
        [95, 66]]])

Jedna od proslijeđenih dimenzija možće biti i broj `1`, dok god je zadovoljen uslov o proizvodu dimenzija.

In [9]:
matrix_np.reshape(3, 8, 1)

array([[[ 9],
        [34],
        [83],
        [ 2],
        [10],
        [96],
        [58],
        [85]],

       [[75],
        [61],
        [ 4],
        [94],
        [18],
        [27],
        [60],
        [79]],

       [[26],
        [63],
        [64],
        [32],
        [17],
        [26],
        [95],
        [66]]])

In [10]:
matrix_np = matrix_np.reshape(4, 6)

**`astype()`** pretvori sve elemente objekta *numpy array* u tip koji se proslijedi kao parametar.  

In [11]:
matrix_np.astype('float32')

array([[ 9., 34., 83.,  2., 10., 96.],
       [58., 85., 75., 61.,  4., 94.],
       [18., 27., 60., 79., 26., 63.],
       [64., 32., 17., 26., 95., 66.]], dtype=float32)

Funkcija **`rand()`** *`np.random`* modula kao paremtar uzima *`tuple`* koji predstavlja oblik (dimenzije) *numpy array*-a kojeg želimo popuniti elementima intervala `[0,1)`.

In [33]:
vector = np.random.rand(6,1)

In [34]:
vector

array([[0.25738503],
       [0.49434521],
       [0.69604821],
       [0.08843022],
       [0.03065612],
       [0.07364478]])

`numpy` biblioteka nudi funkciju `dot()` koja vrši množenje matrica nad proslijeđenim `np.array` nizovima. Proslijeđeni nizovi moraju imati odgovarajuće dimenzije.

In [39]:
vector_2 = np.dot(matrix_np, vector)

In [40]:
vector_2.shape

(4, 1)

In [41]:
matrix_2 = np.random.rand(5,4)*100 #drugi način na koji se može jednostavnije kreirati matrica

In [42]:
matrix_2

array([[97.36468955, 90.14983145, 21.79129603, 67.42288434],
       [31.37965706, 86.75210047, 21.05687731, 19.67897065],
       [79.63566015, 46.5944124 , 66.26954805, 80.06375564],
       [87.16441361,  6.52877204, 73.17421106, 24.40252749],
       [19.7296316 , 44.75906112, 87.724182  , 48.06787256]])

In [43]:
np.dot(matrix_2, vector_2)

array([[24410.46544792],
       [15784.37126848],
       [21512.22165159],
       [14758.04165707],
       [16044.24783889]])

Imitiranje množenja matrice unutar modela neuronske mrže. Prvo definišemo matrice težina. Umanjimo nasumične brojeve za 0.5 kako bi dobili i negativne brojeve, pomnožimo sa 100 i pretvorimo u integer-e. Tako smo osigurali da se sve matrice sastoje od cijelih brojeva koji su veći od -50 i manji od 50.

In [44]:
weights_1 = ((np.random.rand(4,6)-0.5)*100).astype('int64')
weights_2 = ((np.random.rand(5,4)-0.5)*100).astype('int64')
weights_3 = ((np.random.rand(3,5)-0.5)*100).astype('int64')

In [45]:
weights_3

array([[  4,  -1,  24,  37,  38],
       [ 10,  17,   5, -20,  38],
       [  2,  27, -25, -15,  41]], dtype=int64)

Sada se kreira vektor sa kojim ćemo množiti težinske matrice.

In [48]:
x = (np.random.rand(6, 1)-0.5)/5 #njegove koordinate su male kako se ne bi dobili preveliki brojevi pri množenju

In [49]:
np.dot(weights_3, np.dot(weights_2, np.dot(weights_1, x)))

array([[ 13029.76479718],
       [ -9056.66865592],
       [-14455.02981962]])

Kreiramo sad bias-e.

In [50]:
bias_1 = ((np.random.rand(4,1)-0.5)*10)
bias_2 = ((np.random.rand(5,1)-0.5)*10)
bias_3 = ((np.random.rand(3,1)-0.5)*10)

In [51]:
np.dot(weights_3, np.dot(weights_2, np.dot(weights_1, x)+bias_1)+bias_2)+bias_3

array([[ 11201.85354031],
       [-21677.33328627],
       [-28497.98813937]])

I uvodimo još jedan dio iz neuronskih mreža tj. funkciju aktivacije. Koristićemo sigmoid funkciju koja slika $x$ u $\frac{1}{1+e^{-x}}$

In [52]:
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

In [53]:
sigmoid(np.dot(weights_3, sigmoid(np.dot(weights_2, sigmoid(np.dot(weights_1, x)+bias_1))+bias_2))+bias_3)

array([[1.00000000e+00],
       [3.55624166e-08],
       [4.24662519e-16]])