In [1]:
import random
import numpy as np
from tensorflow.keras.utils import to_categorical

In [2]:
numbers = np.array([k+1 for k in range(24)])
random.shuffle(numbers)

In [3]:
numbers

array([20, 10,  1, 11, 15,  7, 21, 17,  5, 13, 24,  6,  2, 12, 23,  3, 18,
       14, 22, 16,  4,  8,  9, 19])

In [3]:
numbers_3d = numbers.reshape(2,3,4)

Funkcija `numpy.where()` vraća indekse elemenata niza koji zadovoljavaju dati uslov. Poziva se nad nizom, a uslov se proslijeđuje kao argument.

In [5]:
numbers_3d

array([[[20, 10,  1, 11],
        [15,  7, 21, 17],
        [ 5, 13, 24,  6]],

       [[ 2, 12, 23,  3],
        [18, 14, 22, 16],
        [ 4,  8,  9, 19]]])

In [6]:
np.where(numbers_3d==24)

(array([0], dtype=int64), array([2], dtype=int64), array([2], dtype=int64))

In [7]:
np.where(numbers_3d>=20)

(array([0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1], dtype=int64),
 array([0, 2, 2, 2, 2], dtype=int64))

In [8]:
np.where(numbers==24)

(array([10], dtype=int64),)

Sa `where()` možemo pronaći indeks elementa u *numpy* nizu. U ovom slučaju smo znali da je maksimalan element 24 i tako pronašli njegovu poziciju. Šta jednostavno možemo uraditi da nađemo poziciju maksimalnog elementa u listi ako ne znamo koji je? Šta bi se moglo uraditi kad imamo matricu da se nađe maksimalan element u svakoj koloni ili redu?

In [4]:
numbers = numbers.reshape(8,3)

In [6]:
numbers

array([[10, 17,  5],
       [21, 20, 23],
       [ 1,  6, 19],
       [11, 13, 18],
       [ 2,  7, 24],
       [ 4, 14,  3],
       [ 8, 16, 15],
       [ 9, 12, 22]])

`argmax()` vraća indeks maksimalnog elementa među svim pojedinačnim elementima u nizu. Ako imamo matricu i ako želimo da nam vraća maksimalan za svaki red možemo proslijediti parametar `axis=1`. Sa `axis=0` možemo vratiti indekse maksimalnih elementa svake kolone.

In [5]:
np.argmax(numbers)

14

In [11]:
max_per_row = np.argmax(numbers, axis=1)

In [12]:
max_per_row

array([0, 1, 0, 1, 2, 1, 0, 2], dtype=int64)

In [14]:
max_per_column = np.argmax(numbers, axis = 0)

In [15]:
max_per_column

array([6, 3, 4], dtype=int64)

`to_categorical()` pretvara vektor klasa, koje su kodirane prirodnim brojevima, u binarnu matricu čiji je broj vrsta jednak broju elemenata vektora, a broj kolona je po default-u jednak 1 +  maksimalni element vektora. Može se i broj klasa proslijediti kao paramtar ali on mora biti veći od maksimalnog elementa vektora + 1.

In [16]:
to_categorical([0,1,2])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [17]:
to_categorical([2,1,0])

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [18]:
to_categorical([1,1,1])

array([[0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [19]:
to_categorical([1,1,1], 3)

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [20]:
to_categorical([2,3,4], 3)

IndexError: index 3 is out of bounds for axis 1 with size 3

In [21]:
to_categorical(max_per_row)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

`to_categorical()` prihvata i realne pozitivne vrijednosti i zaokružuje ih na donji cio dio broja.

In [19]:
categories = [1.4, 2.7, 3, 3, 5.2, 6, 1, 5.2]

In [20]:
to_categorical(categories)

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]], dtype=float32)